version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data://var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
